# -*- coding: utf-8 -*-
"""20/practice sesson project(mosquito)-2copy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zic4ReMcl_FMkVvMBgFQgWK9m-1JJfhU

### Mount the drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Load the CSV file

- Please copy the path of the generate CSV file.
"""

import pandas as pd

CSV_PATH = "/content/drive/MyDrive/AIClub_AP_Damacharla_Harika/Mosquito Project/Dataset/mosquito_feature_extracted.csv"

# read the csv
data = pd.read_csv(CSV_PATH)
data.head()

"""### Check the labels and labels count"""

# label count
data["category"].value_counts()

"""### SPlit the data into train and test

- We use the scikit-learn (another python module) to split the dataset.
- It takes 2 parameters mainly.
    - array - Data to split
    - test_size  - Test size as percentage
- Please make sure you have at least one data point from each category.
- Otherwise re-run this code block
"""

from sklearn.model_selection import train_test_split

# split the dataset
df_train, df_test = train_test_split(data, test_size = 0.2)

# reset the indexes
df_train.reset_index(drop = True, inplace = True)
df_test.reset_index(drop = True, inplace = True)

# test at least one data point is available in the test dataset
# if not re-run this again
df_test["category"].value_counts()

"""### Now save the CSVs
- Please make sure to download the CSVs from colab environment
"""

import os

# define the save folder
SAVE_FOLDER = "/content/drive/MyDrive/AIClub_AP_Damacharla_Harika/Mosquito Project/Dataset/"
TRAIN_CSV = "mosquito_features_train.csv"
TEST_CSV = "mosquito_features_test.csv"

# save the train csv
df_train.to_csv(os.path.join(SAVE_FOLDER, TRAIN_CSV), index = False)
# save the test csv
df_test.to_csv(os.path.join(SAVE_FOLDER, TEST_CSV), index = False)